Repository asigloo/vue-dynamic-forms, pull requests merged in 2020-05, with the labels that each got.

#5 Fix typo in code snippet
  README.md
Labels: bug

#8 Added missing attributes to select options.
  dev/App.vue
  src/components/input-select/InputSelect.vue
Labels: bug, enhancement

#9 Added Repo and Issues to package.json
  package.json
Labels: bug

#11 Try to ignore .git in all subfolders for npm
  .npmignore
Labels: bug

#13 Custom Fields via dynamic scoped slots
  .prettierrc
  dev/App.vue
  dev/assets/pika.png
  package-lock.json
  package.json
  src/components/dynamic-form/DynamicForm.js
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-input/DynamicInput.js
  src/components/dynamic-input/DynamicInput.vue
Labels: feature

#17 Added customClasses and fix small stuff
  dev/App.vue
  src/components/dynamic-form/DynamicForm.js
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-input/DynamicInput.vue
  src/core/utils/form-control.model.js
Labels: bug

#19 Added Spread Form Options and netlify support
  dev/App.vue
  src/components/dynamic-form/DynamicForm.js
  src/components/dynamic-form/DynamicForm.vue
  src/core/utils/form-control.model.js
Labels: enhancement, feature

#22 Input autovalidation on blur
  dev/App.vue
  src/components/dynamic-input/DynamicInput.js
  src/components/dynamic-input/DynamicInput.vue
  src/core/utils/form-control.model.js
Labels: enhancement, feature

#24 Fix textarea issues
  dev/App.vue
  src/components/input-textarea/InputTextarea.vue
  src/core/utils/form-control.model.js
  src/styles/themes/default.scss
Labels: bug

#30 Hotfix textarea methods added
  CHANGELOG.md
  package.json
  src/components/input-textarea/InputTextarea.js
Labels: bug
