Repository asigloo/vue-dynamic-forms, pull requests merged in 2020-10, with the labels that each got.

#148 fix(ci): bringing back semantic release to main
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: 2.x

#150 Semantic release next
  .github/workflows/release.yml
  README.md
  package-lock.json
  package.json
Labels: next

#154 feat(build): add alias to rollup
  dev/typescript/App.vue
  dev/typescript/main.ts
  package-lock.json
  package.json
  rollup.config.js
  src/components/checkbox-input/CheckboxInput.vue
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-input/DynamicInput.vue
  src/components/number-input/NumberInput.vue
  src/components/radio-input/RadioInput.vue
  src/components/select-input/SelectInput.vue
  src/components/text-area-input/TextAreaInput.vue
  src/components/text-input/TextInput.vue
Labels: build, next

#157 fix(types): fix new types usage
  package-lock.json
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-form/form.ts
  src/components/dynamic-input/DynamicInput.vue
  src/composables/input-events.ts
  src/core/models.ts
  src/core/utils/validators.ts
Labels: enhancement, next

#152 Feature/refactor fields logic
  dev/typescript/App.vue
  dev/typescript/main.ts
  dev/vue/App.vue
  dev/vue/styles/_vendors.scss
  package-lock.json
  src/components/checkbox-input/CheckboxInput.vue
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-form/form.ts
  src/components/dynamic-input/DynamicInput.vue
  src/components/number-input/NumberInput.vue
  src/components/radio-input/RadioInput.vue
  src/components/select-input/SelectInput.vue
  src/components/text-area-input/TextAreaInput.vue
  src/composables/input-events.ts
  src/core/models.ts
  src/core/utils/helpers.ts
  src/core/utils/validators.ts
  vue.config.js
Labels: feature, next

#160 fix(types): fix ts exception with non exported subtypes.
  package-lock.json
  package.json
  src/core/models.ts
Labels: build, next

#163 fix(form): add missing condition to fieldOrder sorting
  package-lock.json
  src/components/dynamic-form/DynamicForm.vue
  vue.config.js
Labels: bug, next

#164 fix(events): add condition for control in input-events
  src/composables/input-events.ts
Labels: bug, next

#167 fix(custom-field): add possibility to default number value
  src/core/models.ts
Labels: bug

#170 feat(inputs): improve event handling
  dev/typescript/App.vue
  src/components/checkbox-input/CheckboxInput.vue
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-input/DynamicInput.vue
  src/composables/input-events.ts
  src/core/utils/helpers.ts
Labels: enhancement, next

#171 fix(custom): fix change event on custom field
  .github/workflows/ci.yml
  src/components/dynamic-input/DynamicInput.vue
Labels: bug, next

#176 fix(readme): Added vue3 info to readme
  README.md
  dev/nuxt/package-lock.json
  dev/nuxt/package.json
  package-lock.json
  package.json
Labels: 2.x, documentation

#179 Feature/support aa accesibility
  dev/typescript/App.vue
  package-lock.json
  package.json
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-input/DynamicInput.vue
  src/components/number-input/NumberInput.vue
  src/components/select-input/SelectInput.vue
  src/components/text-area-input/TextAreaInput.vue
  src/components/text-input/TextInput.vue
  src/core/models.ts
Labels: accesibility, next

#180 feat(forms): added CustomStyles attrs to form and inputs
  dev/vue/App.vue
  package-lock.json
  src/components/dynamic-form/DynamicForm.js
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-input/DynamicInput.js
  src/components/dynamic-input/DynamicInput.vue
  src/core/utils/form-control.model.js
Labels: 2.x, enhancement, feature-request

#182 feat(forms): added CustomStyles attr for forms and inputs
  dev/typescript/App.vue
  dev/typescript/main.ts
  package-lock.json
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-input/DynamicInput.vue
  src/core/models.ts
Labels: feature-request, next

#183 feat(input): added readonly attr
  dev/typescript/App.vue
  src/components/number-input/NumberInput.vue
  src/components/select-input/SelectInput.vue
  src/components/text-area-input/TextAreaInput.vue
  src/components/text-input/TextInput.vue
  src/core/models.ts
Labels: feature, next

#185 feat(models): Added new factory functions for fields.
  dev/typescript/App.vue
  dev/vue/App.vue
  src/components/dynamic-form/DynamicForm.vue
  src/components/dynamic-input/DynamicInput.vue
  src/core/factories.ts
  src/core/models.ts
  src/core/utils/validators.ts
  src/index.ts
Labels: feature, next
